/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      colors: {
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
      },
      keyframes: {
        "border-beam":         { "100%": { "offset-distance": "100%" } },
        "border-beam-reverse": { "100%": { "offset-distance": "0%" } },
        meteor: {
          "0%": { transform: "rotate(215deg) translateX(0)", opacity: "1" },
          "70%": { opacity: "1" },
          "100%": { transform: "rotate(215deg) translateX(-500px)", opacity: "0" },
        },
        "retro-grid": {
          "0%":   { transform: "translateY(-33.333%)" },
          "100%": { transform: "translateY(0)" },
        },
        "gradient-text": {
          "0%,100%": { "background-position": "0% 50%" },
          "50%":     { "background-position": "100% 50%" },
        },
        ripple:         { "100%": { transform: "scale(16)", opacity: "0" } },
        "shimmer-slide":{ "0%": { transform: "translateX(-200%) skewX(-15deg)" }, "100%": { transform: "translateX(300%) skewX(-15deg)" } },
        marquee:         { from: { transform: "translateX(0)" },   to: { transform: "translateX(calc(-100% - var(--gap)))" } },
        "marquee-vertical": { from: { transform: "translateY(0)" }, to: { transform: "translateY(calc(-100% - var(--gap)))" } },
        "fade-up":  { from: { opacity: "0", transform: "translateY(16px) scale(0.98)" }, to: { opacity: "1", transform: "none" } },
        "fade-in":  { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-down":{ from: { opacity: "0", transform: "translateY(-12px) scale(0.98)" }, to: { opacity: "1", transform: "none" } },
        skeleton:   { "0%": { "background-position": "-600px 0" }, "100%": { "background-position": "600px 0" } },
        "live-dot": { "0%,100%": { opacity: "1", transform: "scale(1)" }, "50%": { opacity: "0.4", transform: "scale(0.85)" } },
        float:      { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
        "spin-slow": { to: { transform: "rotate(360deg)" } },
        "slide-down":{ from: { opacity: "0", transform: "translateY(-14px) scale(0.97)" }, to: { opacity: "1", transform: "none" } },
        "neon-border":{ to: { "--neon-angle": "360deg" } },
      },
      animation: {
        "border-beam":         "border-beam calc(var(--duration)*1s) infinite linear",
        "border-beam-reverse": "border-beam-reverse calc(var(--duration)*1s) infinite linear",
        meteor:                "meteor var(--duration,6s) linear infinite",
        "retro-grid":          "retro-grid 12s linear infinite",
        "gradient-text":       "gradient-text 4s ease infinite",
        ripple:                "ripple 0.6s linear forwards",
        "shimmer-slide":       "shimmer-slide 2.2s ease infinite",
        marquee:               "marquee var(--duration,20s) linear infinite",
        "marquee-vertical":    "marquee-vertical var(--duration,20s) linear infinite",
        "fade-up":             "fade-up 0.5s cubic-bezier(0.16,1,0.3,1) both",
        "fade-in":             "fade-in 0.3s ease both",
        "fade-down":           "fade-down 0.35s cubic-bezier(0.16,1,0.3,1) both",
        skeleton:              "skeleton 1.6s infinite linear",
        "live-dot":            "live-dot 2s ease-in-out infinite",
        float:                 "float 3s ease-in-out infinite",
        "spin-slow":           "spin-slow 3s linear infinite",
        "slide-down":          "slide-down 0.35s cubic-bezier(0.16,1,0.3,1) both",
        "neon-border":         "neon-border 3s linear infinite",
      },
    },
  },
  plugins: [],
};
